# Server Configuration
server.port=${SERVER_PORT:8080}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/api}

# Application Name
spring.application.name=${SPRING_APPLICATION_NAME:cineSk}

# Database Configuration
spring.datasource.url=${DATABASE_HOST}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.properties.hibernate.connection.charset=${SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_CHARSET}

# Logging Configuration
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.com.cine.sk=${LOGGING_LEVEL_COM_CINE_SK:DEBUG}